import type { Metadata } from "next";
import { Inter, Afacad } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { Toaster } from "@/components/ui/sonner";
import QueryProvider from "@/providers/query-client.provider";
import AuthProvider from "@/providers/auth.provider";
import { getSession } from "@/lib/get-session";
import { CartType } from "@/lib/types";
import { getCart } from "@/lib/get-cart";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

const afacad = Afacad({
  subsets: ["latin"],
  variable: "--font-afacad",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  let cart: CartType | null = null;
  const session = await getSession();

  if (session) {
    cart = await getCart(session.access_token);
  }

  return (
    <html
      lang="en"
      className={cn("font-sans", inter.variable, afacad.variable)}
    >
      <body>
        <QueryProvider>
          <AuthProvider session={session} cart={cart}>
            <Header />
            {children}
            <Footer />
            <Toaster />
          </AuthProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
