import { createFileRoute } from '@tanstack/react-router'

export const Route = createFileRoute('/privacy-policy')({
  component: RouteComponent,
})

function RouteComponent() {
  return (
    <div>
      <div className="bg-[#fbf4e1] py-10 text-[#194455]">
        <div className="container mx-auto">
          <h1 className="afacad-flux text-4xl text-center font-semibold tracking-wider">
            Privacy Policy
          </h1>
          <p className="text-center text-lg tracking-wider">
            Home / Privacy Policy
          </p>
        </div>
      </div>
      <section className="py-10">
        <div className="container mx-auto">
          <p>
            <span className="font-light">
              Our Privacy Policy governs your visit to www.mitvana.com, and
              explains how we collect, safeguard and disclose information that
              results from your use of our Service. We use your data to provide
              and improve Service. By using Service, you agree to the collection
              and use of information in accordance with this policy. Unless
              otherwise defined in this Privacy Policy, the terms used in this
              Privacy Policy have the same meanings as in our Terms and
              Conditions. Our Terms and Conditions (“Terms”) govern all use of
              our Service and together with the Privacy Policy constitutes your
              agreement with us (“agreement”).
            </span>
          </p>
          <p>
            <br />
            <b>DEFINITIONS</b>
          </p>
          <br />
          <p>
            <span className="font-light">
              SERVICE means the www.mitvana.com website operated by Matxin Labs
              Pvt. Ltd..{' '}
            </span>
            <span className="font-light">
              <br />
            </span>
            <span className="font-light">
              PERSONAL DATA means data about a living individual who can be
              identified from those data (or from those and other information
              either in our possession or likely to come into our
              possession).{' '}
            </span>
            <span className="font-light">
              <br />
            </span>
            <span className="font-light">
              USAGE DATA is data collected automatically either generated by the
              use of Service or from Service infrastructure itself (for example,
              the duration of a page visit).{' '}
            </span>
            <span className="font-light">
              <br />
            </span>
            <span className="font-light">
              COOKIES are small files stored on your device (computer or mobile
              device).{' '}
            </span>
            <span className="font-light">
              <br />
            </span>
            <span className="font-light">
              DATA CONTROLLER means a natural or legal person who (either alone
              or jointly or in common with other persons) determines the
              purposes for which and the manner in which any personal data are,
              or are to be, processed. For the purpose of this Privacy Policy,
              we are a Data Controller of your data.{' '}
            </span>
            <span className="font-light">
              <br />
            </span>
            <span className="font-light">
              DATA PROCESSORS (OR SERVICE PROVIDERS) means any natural or legal
              person who processes the data on behalf of the Data Controller. We
              may use the services of various Service Providers in order to
              process your data more effectively.{' '}
            </span>
            <span className="font-light">
              <br />
            </span>
            <span className="font-light">
              DATA SUBJECT is any living individual who is the subject of
              Personal Data.{' '}
            </span>
            <span className="font-light">
              <br />
            </span>
            <span className="font-light">
              THE USER is the individual using our Service. The User corresponds
              to the Data Subject, who is the subject of Personal Data.
            </span>
          </p>
          <p>
            <br />
            <b>WHAT DO WE DO WITH YOUR INFORMATION?</b>
          </p>
          <br />
          <p>
            <span className="font-light">
              When you purchase something from our www.mitvana.com, as part of
              the buying and selling process, we collect the personal
              information you give us such as your name, address and email
              address.
            </span>
          </p>
          <p>
            <span className="font-light">
              When you browse www.mitvana.com, we also automatically receive
              your computer’s internet protocol (IP) address in order to provide
              us with information that helps us learn about your browser and
              operating system.
            </span>
          </p>
          <p>
            <span className="font-light">
              Email marketing (if applicable): With your permission, we may send
              you emails about&nbsp; www.mitvana.com, new products and other
              updates.
            </span>
          </p>
          <p>
            <br />
            <b>CONSENT</b>
          </p>
          <br />
          <p>
            <span className="font-light">How do you get my consent?</span>
          </p>
          <p>
            <span className="font-light">
              When you provide us with personal information to complete a
              transaction, verify your credit card, place an order, arrange for
              a delivery or return a purchase, we imply that you consent to our
              collecting it and using it for that specific reason only.
            </span>
          </p>
          <p>
            <span className="font-light">
              If we ask for your personal information for a secondary reason,
              like marketing, we will either ask you directly for your expressed
              consent, or provide you with an opportunity to say no.
            </span>
          </p>
          <p>
            <span className="font-light">
              How do I withdraw my consent for using my personal information for
              secondary reason?
            </span>
          </p>
          <p>
            <span className="font-light">
              If after you opt-in, you change your mind, you may withdraw your
              consent for us to contact you, for the continued collection, use
              or disclosure of your information, at anytime, by contacting us at
              Company Contact Email: info@matxinlabs.com&nbsp;
            </span>
            <span>
              in or mailing us at: Matxin Labs Pvt Ltd, L-21, F-4, sector-14,
              JeevanBhima Nagar, Bangalore-560075, Karnataka, India.
            </span>
          </p>
          <p>
            <br />
            <b>DISCLOSURE</b>
          </p>
          <br />
          <p>
            <span className="font-light">
              We may disclose your personal information if we are required by
              law to do so or if you violate our Terms of Service.
            </span>
          </p>
          <p>
            <br />
            <b>PAYMENT</b>
          </p>
          <br />
          <p>
            <span className="font-light">
              We use Razorpay for processing payments. We/Razorpay do not store
              your card data on their servers. The data is encrypted through the
              Payment Card Industry Data Security Standard (PCI-DSS) when
              processing payment. Your purchase transaction data is only used as
              long as is necessary to complete your purchase transaction. After
              that is complete, your purchase transaction information is not
              saved.
            </span>
          </p>
          <p>
            <span className="font-light">
              Our payment gateway adheres to the standards set by PCI-DSS as
              managed by the PCI Security Standards Council, which is a joint
              effort of brands like Visa, MasterCard, American Express and
              Discover.
            </span>
          </p>
          <p>
            <span className="font-light">
              PCI-DSS requirements help ensure the secure handling of credit
              card information by our store and its service providers.
            </span>
          </p>
          <p>
            <span className="font-light">
              For more insight, you may also want to read terms and conditions
              of razorpay on{' '}
            </span>
            <a href="https://razorpay.com">
              <span className="font-light">https://razorpay.com</span>
            </a>
          </p>
          <p>
            <br />
            <b>THIRD-PARTY SERVICES</b>
          </p>
          <br />
          <p>
            <span className="font-light">
              In general, the third-party providers used by us will only
              collect, use and disclose your information to the extent necessary
              to allow them to perform the services they provide to us.
            </span>
          </p>
          <p>
            <span className="font-light">
              However, certain third-party service providers, such as payment
              gateways and other payment transaction processors, have their own
              privacy policies in respect to the information we are required to
              provide to them for your purchase-related transactions.
            </span>
          </p>
          <p>
            <span className="font-light">
              For these providers, we recommend that you read their privacy
              policies so you can understand the manner in which your personal
              information will be handled by these providers.
            </span>
          </p>
          <p>
            <span className="font-light">
              In particular, remember that certain providers may be located in
              or have facilities that are located a different jurisdiction than
              either you or us. So if you elect to proceed with a transaction
              that involves the services of a third-party service provider, then
              your information may become subject to the laws of the
              jurisdiction(s) in which that service provider or its facilities
              are located.
            </span>
          </p>
          <p>
            <span className="font-light">
              Once you leave our store’s website or are redirected to a
              third-party website or application, you are no longer governed by
              this Privacy Policy or our website’s Terms of Service.
            </span>
          </p>
          <p>
            <span className="font-light">Third Party Links</span>
          </p>
          <p>
            <span className="font-light">
              When you click on links on our store, they may direct you away
              from our site. We are not responsible for the privacy practices of
              other sites and encourage you to read their privacy statements.
            </span>
          </p>
          <p>
            <br />
            <b>SECURITY OF DATA</b>
          </p>
          <br />
          <p>
            <span className="font-light">
              To protect your personal information, we take reasonable
              precautions and follow industry best practices to make sure it is
              not inappropriately lost, misused, accessed, disclosed, altered or
              destroyed.
            </span>
          </p>
          <p>
            <br />
            <b>COOKIES</b>
          </p>
          <br />
          <p>
            <span className="font-light">
              We use cookies to maintain session of your user. It is not used to
              personally identify you on other websites. Cookies are files with
              a small amount of data which may include an anonymous unique
              identifier. Cookies are sent to your browser from a website and
              stored on your device. Other tracking technologies are also used
              such as beacons, tags and scripts to collect and track information
              and to improve and analyse our Service. You can instruct your
              browser to refuse all cookies or to indicate when a cookie is
              being sent. However, if you do not accept cookies, you may not be
              able to use some portions of our Service.
            </span>
          </p>
          <p>
            <br />
            <b>AGE OF CONSENT</b>
          </p>
          <br />
          <p>
            <span className="font-light">
              By using this site, you represent that you are at least the age of
              majority in your state or province of residence, or that you are
              the age of majority in your state or province of residence and you
              have given us your consent to allow any of your minor dependents
              to use this site.&nbsp;
            </span>
          </p>
          <p>
            <span className="font-light">
              Our Services are not intended for use by children under the age of
              18 (“Child” or “Children”). We do not knowingly collect personally
              identifiable information from Children under 18. If you become
              aware that a Child has provided us with Personal Data, please
              contact us. If we become aware that we have collected Personal
              Data from Children without verification of parental consent, we
              take steps to remove that information from our servers.
            </span>
          </p>
          <p>
            <br />
            <b>CHANGES TO THIS PRIVACY POLICY</b>
          </p>
          <br />
          <p>
            <span className="font-light">
              We may update our Privacy Policy from time to time. We reserve the
              right to modify this privacy policy, so please review it
              frequently. Changes and clarifications will take effect
              immediately upon their posting on{' '}
            </span>
            <span className="font-light">www.mitvana.com</span>
            <span className="font-light">
              . If we make material changes to this policy, we will notify you
              here that it has been updated, so that you are aware of what
              information we collect, how we use it, and under what
              circumstances, if any, we use and/or disclose it.
            </span>
          </p>
          <p>
            <span className="font-light">
              If our store is acquired or merged with another company, your
              information may be transferred to the new owners so that we may
              continue to sell products to you.
            </span>
          </p>
          <p>
            <br />
            <b>QUESTIONS AND CONTACT INFORMATION</b>
          </p>
          <br />
          <p>
            <span className="font-light">
              If you would like to: access, correct, amend or delete any
              personal information we have about you, register a complaint, or
              simply want more information contact our Privacy Compliance
              Officer at –&nbsp;
            </span>
            <span>Email:&nbsp;</span>
            <span>info@matxinlabs.com</span>
            <span>&nbsp;or by mail to</span>
          </p>
          <p>
            <span className="font-light">[Re: Privacy Compliance Officer]</span>
          </p>
          <br />
          <div>
            <h6>
              <strong>
                Matxin Labs Pvt Ltd,
                <br />
                No: L-21, F-4, Sector-14, JeevanBhima Nagar
                <br />
                Bangalore-560075
                <br />
                Karnataka, India
              </strong>
            </h6>
          </div>
        </div>
      </section>
    </div>
  )
}
